version: 2
jobs:
  build:
    docker:
      - image: minepicco/cc-build-image:1.0

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build -t "docker-local."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: JFrogCLI config
          command: |
            /jfrog rt config --user=$user --password=$password --url="http://"$jfqdn"/artifactory" $jid
            /jfrog rt ping
      - run:
          name: JFrogCLI artifact publish
          command: |
           /jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
           /jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM docker-local
