version: 2
jobs:
  build:
    docker:
      - image: minepicco/cc-build-image:1.0

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build -t "docker."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: Login and push
          command: |
            docker login $repo  -u $user -p $password
            docker push "docker."$jfqdn"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM



