version: 2
jobs:
  build:
    docker:
      - image: circleci/php

    steps:
      - checkout

      - run:
          name: Build Image
          command: |
            sudo docker build -t $repo"/web:1.1" .
            sudo docker images

      - run:
          name: Login
          command: sudo docker login $repo  -u $user -p $password
          
      - run:
          name: Push image
          command: sudo docker push $repo"/web:1.1"
