version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker:latest

    steps:
      - checkout

      - run:
          name: Build Image
          command: |
            sudo docker build -t $image .
            sudo docker images

      - run:
          name: Login
          command: sudo docker login $repo  -u $user -p $password
          
      - run:
          name: Push image
          command: sudo docker push $image
