version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker:latest

    steps:
      - checkout

      - run:
          name: Build Image
          command: |
            docker build -t $repo"/web:1.1" .
            docker images

      - run:
          name: Login
          command: docker login $repo  -u $user -p $password
          
      - run:
          name: Push image
          command: docker push $repo"/web:1.1"
