version: 2
jobs:
  build:
    docker:
      - image: minepicco/cc-build-image:1.0

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build -t "docker."$jfqdn"/web:"$CIRCLE_PROJECT_REPONAME .

      - run:
          name: Login
          command: docker login $repo  -u $user -p $password
          
      - run:
          name: Push image
          command: docker push "docker."$jfqdn"/web:"$CIRCLE_PROJECT_REPONAME
          

