version: 2
jobs:
  build:
    docker:
      - image: circleci/php

    steps:
      - checkout

      - run:
          name: Build Image
          command: |
            # wget -qO- https://get.docker.com/ | sh
            docker ps
            docker build -t $repo"/web:1.1" .
            docker images

      - run:
          name: Login
          command: docker login $repo  -u $user -p $password
          
      - run:
          name: Push image
          command: docker push $repo"/web:1.1"
